### ISSUE TITLE
discardKeywords没有用

### ISSUE THREAD

**Issue by callzhang** [geekdada/surgio#100]
```
const { utils } = require('surgio');

module.exports = {
  url: 'https://losadhwselfff2332dasd.xyz/link/xxx?mu=0',
  type: 'shadowsocksr_subscribe',
  // 定义所有的节点都支持 udpRelay
  udpRelay: true,
  // 添加国旗 emoji
  addFlag: true,
  customFilters: {
    subscribeFilter: utils.discardKeywords(['地址','流量','时间','Free','续费','官网','回国','用户','设定'], false),
  },
};
```
结果中并没有过滤掉带有关键词名字的服务器

**Comment by geekdada** [comment]
这个功能是没有问题的，请检查使用方法是否有错

**Comment by callzhang** [comment]
使用方法的代码已经贴出来了。使用方法我读了说明也没有说啊，都是我猜的。这样的回答（使用方法有误）并没有任何帮助。我们并不是小白，如果能看懂你文档，或者有例子说明，那我们自然不需要来问了。这样的口气好像是别人能力的问题，无益于一个开源项目的推广。

**Comment by geekdada** [comment]
EASY MAN

没有别的意思，因为从你贴的代码来看是没有问题的，我也可以确认的是这个功能目前是可用的。

最简单的办法就是你新建一个可复现的仓库，我帮你看一下。

**Comment by callzhang** [comment]
repo上传到[这里](https://github.com/callzhang/Surgio)了，辛苦看一下，谢谢！

**Comment by geekdada** [comment]
貌似是 Private 的，加我到 member 里吧

**Comment by callzhang** [comment]
> 貌似是 Private 的，加我到 member 里吧

不好意思，没注意自动生成private了，已经加您了。

**Comment by geekdada** [comment]
定义倒是没问题，但是模板里没有看到哪里有用啊

**Comment by callzhang** [comment]
哦，我就是用`clash`的模板改的，然后生成的`stardust.yaml`里面的结果包含了期待过滤关键词的节点。

**Comment by geekdada** [comment]
你的 `clash.tpl` 没有看到有 `customFilters.subscribeFilter`

**Comment by geekdada** [comment]
你把这个方法的定义放到 Provider 的 `nodeFilter` 上吧

**Comment by callzhang** [comment]
好的我试试，谢谢！

**Comment by callzhang** [comment]
`nodeFilter`可以用`discardKeywords`吗？
`customFilters.subscribeFilter`这个如何定义呢？没找到文档。
我没写过node所以问题可能比较初级😅

**Comment by geekdada** [comment]
https://surgio.royli.dev/guide/custom-template.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%9F

**Comment by callzhang** [comment]
在template里面定义filter不太好，因为provider里面需要过滤的节点是通用的规则，而且template里面已经用了filter了。
在provider里面定义filter这件事情目前仍然没有解决，discardKeywords不行啊，请看看哪里有问题。

**Comment by geekdada** [comment]
- template 中使用，不是定义。
- provider 中定义后要在 template 中使用才会生效。

**Comment by callzhang** [comment]
那建议增加直接在provider里面过滤的方法

**Comment by geekdada** [comment]
https://surgio.royli.dev/guide/custom-provider.html#provider-nodefilter 这个呢？

**Comment by callzhang** [comment]
你的意思是这样吗？：
```
module.exports = {
  // 过滤出名字中包含土耳其和马来西亚的节点
  nodeFilter: utils.discardKeywords(['土耳其', '马来西亚']),
};
```

**Comment by geekdada** [comment]
是
