### ISSUE TITLE
使用了combineProviders后，tpl里面是getClashNodeNames能否将不同Provider分开

### ISSUE THREAD

**Issue by Dark-Existed** [geekdada/surgio#114]
在proxy-groups里面想为每家机场单独创建独立的组  
目前的话可能只能用filter来处理？
有的机场命名是很难全部匹配出来 
不然就要 filter写很多才能实现
想问问有实现这个功能的方法吗

**Comment by geekdada** [comment]
https://surgio.royli.dev/guide/advance/custom-filter.html#useproviders
