### ISSUE TITLE
US Flag Misuse

### ISSUE THREAD

**Issue by dd4rk** [geekdada/surgio#115]
https://github.com/geekdada/surgio/blob/4eafd735be8f5b2d0c34b28630c48b294eafa629/lib/misc/flag_cn.ts#L43

US flag here is using [U+1F1FA U+1F1F2](https://unicode.org/emoji/charts/full-emoji-list.html#1f1fa_1f1f2) which refers to U.S. Outlying Islands, not United States, although the flag looks the same. I suggest use [U+1F1FA U+1F1F8](https://unicode.org/emoji/charts/full-emoji-list.html#1f1fa_1f1f8) instead.

This issue causes conflicts with Quantumult X third-party resource parser when using `addFlag` option.

**Comment by geekdada** [comment]
This really is the most interesting issue I've ever received. OK, a patch is coming your way.
