### ISSUE TITLE
Support merging multi providers into one artifact

### ISSUE THREAD

**Issue by sorcererxw** [geekdada/surgio#24]
I have several providers, and I want to subscribe them via a single url.

If it can be like the following, it might be better.

```
{
      name:'clash.yaml',
      template:'clash',
      provider: [ 'provider_1', 'provider_2' ]
}
```

**Comment by tediorelee** [comment]
> I have several providers, and I want to subscribe them via a single url.
> 
> If it can be like the following, it might be better.
> 
> ```
> {
>       name:'clash.yaml',
>       template:'clash',
>       provider: [ 'provider_1', 'provider_2' ]
> }
> ```

you can add as recipe like this: 
`name: 'Clash.yml',
      template: 'clash',
      provider: 'shadowsocks',
      recipe: ['shadowsocks','v2rayn','blinkload'],`

**Comment by sorcererxw** [comment]
It work! But  what is `recipe` different from `provider`?

**Comment by geekdada** [comment]
@sorcererxw I might bring changes to the API in the future, so the feature is undocumented.

**Comment by sorcererxw** [comment]
@geekdada Thx
