### ISSUE TITLE
两点小建议

### ISSUE THREAD

**Issue by Apocalypsor** [geekdada/surgio#33]
1.在内置的新加坡过滤器中麻烦添加”狮城“关键词；
2.Clash之前的dev已经支持snell了，可以加上；

还有就是请问Surge的Temple中无法使用Provider中自定义的过滤器吗？
Surgio真的是超级好用，开发者辛苦了！

**Comment by geekdada** [comment]
Snell 会在近期加上。

你再检查一下有没有配置错，没有这个限制。

感谢！

**Comment by Apocalypsor** [comment]
我是如下配置的
Provider中配置：
  ```
customFilters: {
    hkFFilter: nodeConfig => nodeConfig.nodeName.includes(['香港']),
  },
```
Surge的模板的[Proxy Group]块中配置
```
HK = select, {{ getNodeNames(nodeList, hkFFilter) }}
```
可是它并没有选出带香港字样的节点
![avatar](https://img.917605.xyz/images/2019/11/07/7mXveQEBYiqGyCZs.png)
请问我的配置有误吗
ps：我的customFilters在Clash配置中是可用的

**Comment by geekdada** [comment]
Clash 和其它情况有些不同。`tpl` 文件中需要使用 `customFilters.hkFFilter`。文档里有写，注意看文档。

**Comment by geekdada** [comment]
目前的新版本应该已经可以识别「狮城」了

**Comment by Apocalypsor** [comment]
不好意思光顾着看clash那部分了😂，非常感谢大佬！
