### ISSUE TITLE
模板中自定义函数扩展支持

### ISSUE THREAD

**Issue by lifesign** [geekdada/surgio#54]
目前 surgio 中内置了一些函数，如 yaml、base64、clash 等
{{ clashProxyConfig | yaml }}
{{ getQuantumultNodes(nodeList, providerName) | base64 }}

是否可以考虑增加用户自定义的函数扩展，这样的好处是可以让用户自定义输出格式，从而兼容更多的客户端模板，而这部分客户端往往不一定是主流的以及 surgio 需要兼容的

类似 {{ getNodeNames(nodeList) | customFunction }}

**Comment by geekdada** [comment]
这样的功能会涉及 Nunjucks 的拓展，我觉得会有些复杂。其实如果需要你完全可以在 customParams 中定义方法，然后 `{{ customFunction(getNodeNames(nodeList)) }}` 达到你的目的。

**Comment by lifesign** [comment]
也可以实现 就是不太优雅 哈哈 。
还有一个问题是 getQuantumultNodes 类似这种方法有没有办法自定义，现在还是有一些客户端的节点生成不是常规的几种

**Comment by geekdada** [comment]
你也可以在 customParams 上拓展你的生成函数。传入的 nodeList 是结构化对象，你可以根据自己的需要组织数据。

**Comment by lifesign** [comment]
好的 我试下吧

**Comment by geekdada** [comment]
This issue is closed because of inactivity.
