### ISSUE TITLE
合并机场订阅后无法显示流量通知

### ISSUE THREAD

**Issue by denyot** [geekdada/surgio#58]
合并多个provider后，quantumult x 无法显示机场流量。
直接使用机场提供的 ssr 链接时，quantumult x 会从链接中获取Response Headers，从而显示流量。
希望支持合并多个 provider 之后，依然支持 surge/quantumult x等工具显示某个机场流量。

**Comment by geekdada** [comment]
之前不知道这个功能。不过如果有多个 API 都返回了这个字段应该如何处理呢？

**Comment by denyot** [comment]
> 之前不知道这个功能。不过如果有多个API都返回了这个变量应该如何处理呢？

有的API 处理这个问题是直接后面的订阅覆盖前面的。 这边建议设置一个参数，用户可以自己选择显示哪个provider 的流量，如果没有传参，那默认显示第一个。 您觉得这样如何呢！ 
 个人愚见，供参考。

**Comment by terranc** [comment]
怎么合并多个机场订阅的？ @denyot
