### ISSUE TITLE
为Surge for Mac external proxy provider生成的v2ray配置无法运行

### ISSUE THREAD

**Issue by ladit** [geekdada/surgio#59]
最新的v2ray下，手动运行生成的config提示端口解析失败，因为是go解析，配置中的端口格式基本要求是Number类型的json字段，而Surgio生成的是String类型，希望能修复一下。
不过beta版的surge提供了native v2ray支持，在代码里好像有看到为native生成，该如何使用呢？
感谢作者的项目！

**Comment by geekdada** [comment]
Native 方式运行的文档 https://surgio.royli.dev/guide/custom-config.html#surgeconfig

**Comment by geekdada** [comment]
那个问题我看一下
