### ISSUE TITLE
大大请问Richcloud的SSR订阅返回403怎么处理呢

### ISSUE THREAD

**Issue by harryyifei** [geekdada/surgio#60]
具体报错信息如下：

HTTPError: 获取 rixcloud_ssr 节点时出现错误，相关文件 /var/task/provider/rixcloud_ssr.js ，错误原因: Response code 403 (Forbidden)

Stack:

HTTPError: 获取 rixcloud_ssr 节点时出现错误，相关文件 /var/task/provider/rixcloud_ssr.js ，错误原因: Response code 403 (Forbidden)
    at EventEmitter.emitter.on (/var/task/node_modules/got/dist/source/as-promise.js:118:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by geekdada** [comment]
这是在使用网关还是本地运行时报错的？

**Comment by harryyifei** [comment]
使用网关的时候

**Comment by geekdada** [comment]
Rixcloud 把绝大多数云服务的 IP 都封锁了，你要自己使用转发服务
