### ISSUE TITLE
在下载规则途中停止，且没有任何报错信息

### ISSUE THREAD

**Issue by L0snight** [geekdada/surgio#64]
在运行的过程中，出现了下载过程中就停止运行的情况，且过程中没有报错。之前用的时候没有这种问题。
系统:Arch Linux
surgio version: 1.13.4
网络情况: 透明代理，可任意访问外网
截图：
![image](https://user-images.githubusercontent.com/19932520/76270801-6ddaa300-62b1-11ea-8f3b-16bfda078759.png)

**Comment by geekdada** [comment]
使用 LTS 版本的 Nodejs 即可
