### ISSUE TITLE
新版 API 自定义过滤器的问题

### ISSUE THREAD

**Issue by huangyafei** [geekdada/surgio#65]
为什么在新版 API 下，在 `surgio.conf.js` 里定义了自定义过滤器但在 template 中没有使用的话，网关就报错呢？旧版本定义了自定义过滤器但没有使用，是可以正常跑起来的。

我目前的使用习惯是自定义过滤器不一定在模板中使用，比较多的是使用 get-artifact 加参数的方式筛选出一些节点来用，现在在 `surgio.conf.js`定义了过滤器就必须要用的方式，感觉没有之前灵活了。

**Comment by geekdada** [comment]
没有这样的设定，应该是你的过滤器内有语法错误

**Comment by huangyafei** [comment]
`surgio.conf.js` 里过滤器是这么写的，好像格式是没问题的哈？

```
'use strict';
const { categories } = require('surgio');
module.exports = {
  customFilters: {
    hktFilter: utils.useKeywords(['hkt', 'HKT']),
  },
artifacts: [
...
]
```

**Comment by geekdada** [comment]
```js
const { categories, utils } = require('surgio');
```

**Comment by huangyafei** [comment]
我明白了，谢谢大大。
