### ISSUE TITLE
求一个新Feature，关于策略组复用的。

### ISSUE THREAD

**Issue by denyot** [geekdada/surgio#78]
大大，您好！   
           有没有办法实现 proxy group 复用呢？类似现在对规则Snippet那样的处理方式。
定义一个 surge 通用的 proxy group 作为模板，clash、Quantumult X 等工具都以 surge 格式的 proxy group 的模板转化而来。这样对于同时维护 surge 、clash、quantumultx三种配置工具来说，真是非常棒。

**Comment by geekdada** [comment]
建议仔细看看 Nunjucks 的文档，没准可以找到解决方案。

**Comment by lwQin** [comment]
关掉的 issues 里有说解决方案 #69

**Comment by lwQin** [comment]
> 大大，您好！   
> 
>            有没有办法实现 proxy group 复用呢？类似现在对规则Snippet那样的处理方式。
> 
> 定义一个 surge 通用的 proxy group 作为模板，clash、Quantumult X 等工具都以 surge 格式的 proxy group 的模板转化而来。这样对于同时维护 surge 、clash、quantumultx三种配置工具来说，真是非常棒。
> 
> 

关掉的 issues 里有解决方案 #69

**Comment by geekdada** [comment]
@lwQin Nice！
