### ISSUE TITLE
getMellowNodes()函数

### ISSUE THREAD

**Issue by LGTMXD** [geekdada/surgio#91]
测试订阅 `https://jiang.netlify.app/`

得到的vmess节点缺少：
`&ws.host=example.com
`

`&http.host=example.com%2Cexample1.com
`

`&tls.allowinsecure=true`

**Comment by geekdada** [comment]
1. 按照这里 https://github.com/v2ray/v2ray-core/issues/1569 的定义，不应该是 `ws.host` 而是 `ws.headers.host` 才对吧？
2. 目前仅支持 tcp 和 ws 类型的节点解析，所以 http 暂不增加；

**Comment by geekdada** [comment]
@LGTMXD 麻烦回答一下上面的回复

**Comment by LGTMXD** [comment]
> 1. 按照这里 v2ray/v2ray-core#1569 的定义，不应该是 ws.host 而是 ws.headers.host，对吧？

**按照v2ray那里的定义是这样的，但是mellow里面用的是ws.host**

> 2.目前仅支持 tcp 和 ws 类型的节点解析，所以 http 暂不增加；

**ok**

**Comment by geekdada** [comment]
知道了
