### ISSUE TITLE
生成的 Clash 配置中，Bool 值加引号后现在会报错

### ISSUE THREAD

**Issue by AzunyanDaisuki** [geekdada/surgio#97]
![bool](https://user-images.githubusercontent.com/18110400/85721286-ced49c80-b723-11ea-9aeb-d91dc91e964e.png)
我看了一下节点信息里写的是 "udp": "true"，被认为是字符串了

**Comment by geekdada** [comment]
了解

**Comment by geekdada** [comment]
如果你用的是 custom 类型的 provider，在定义 udp-relay 时用的是不是字符串，还是别的 provider？

**Comment by AzunyanDaisuki** [comment]
我用的是 clash 类型的 provider。 udp-relay 确实用的是字符串。但奇怪的是，文档里说如果节点信息包含了 udp，这一配置无效，但我订阅的机场节点信息中有的包含 udp，也变成了字符串，甚至 udp: false 的也变成了 "udp":"true"
我把 provider 中 udp-relay 的定义改成了 boolean 值后确实输出 boolean 值了，但 false 还是变成了 true，并没有被忽略掉。

**Comment by geekdada** [comment]
provider 中的 udp-relay 会覆盖机场给的 udp。类型错误这个问题我会在下个版本中修复。

**Comment by AzunyanDaisuki** [comment]
好的，非常感谢。

**Comment by geekdada** [comment]
我看了一下，目前的版本里其实已经不允许在 clash provider 中设置除 `boolean` 类型之外的 `udpRelay`，请问一下你的版本是多少？

**Comment by AzunyanDaisuki** [comment]
是 1.24.3
我又试了一下，在 clash provider 里设置 udpRelay: 'true' 确实会生成 'udp':'true'
这样设置之后
![image](https://user-images.githubusercontent.com/18110400/86205807-6c552380-bb9d-11ea-9610-7c0d303d77c4.png)
生成了这样的 proxy
![image](https://user-images.githubusercontent.com/18110400/86205769-4a5ba100-bb9d-11ea-870b-a4080cfe7253.png)

**Comment by geekdada** [comment]
启动时有一个类型检查，应该报错才对，你还是要用 boolean 才行

**Comment by AzunyanDaisuki** [comment]
但奇怪的是，我写了 string 的值，执行 npx surgio generate，一路没有报错地生成了 string 值的配置，导致在 clash 里因为类型不匹配出错了，改成 boolean 当然没有问题

**Comment by geekdada** [comment]
我知道问题在哪了，下个版本修了
