### ISSUE TITLE
是否可以增加对SSD订阅文件的解析？

### ISSUE THREAD

**Issue by callzhang** [geekdada/surgio#99]
ss的订阅一般都以ssd方式发布吧？

**Comment by geekdada** [comment]
暂不考虑，Clash 是目前兼容性最好的订阅方式。今后如果想要的人多了再提供吧。

**Comment by geekdada** [comment]
先不关闭 Issue，如果有其他人需要这个功能可以在这里评论。

**Comment by geekdada** [comment]
已增加 https://github.com/geekdada/surgio/releases/tag/v2.0.0
